Added units of measurement
HumanBrainProject/openMINDS_controlledTerms pull request #140
Opened 2022-03-02 10:02 UTC by MaaikevS

Related to Issue #134

2022-03-04 09:11 UTC, lzehl requested changes

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/degree.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/unitOfMeasurement/degree",
This one should be specified/changed:
+ arcdegree (synonyms: degree of arc, degree, arc degree;) VS
+ degreeCelcius (degree of temperature; as you have below)
+ degreeFahrenheit (degree of temperature; synonym: degree)
+ degreeRankine (degree of temperature; synonym: degree)

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/microgramPerMilliliter.jsonld
> +    "ug/ml"
this should be also including a true `µg/ml`

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/micromolar.jsonld
> +    "10^-6 mol/L",
this I would delete.

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/micromolar.jsonld
> +    "10^-3 mol/m^3"
this I would delete

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/micromolar.jsonld
> +    "uM",
should include `µM`

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/degreeCelsius.jsonld
> +  "synonym": null
degree

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/milligramPerKilogramBodyWeight.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/unitOfMeasurement/milligramPerKilogramBodyWeight",
this is not a unit. "milligram per kilogram" is the unit. That the kg is based on the body weight is context specific (case in which the unit is used).

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/millimolar.jsonld
> +    "10^-3 mol/L",
I would delete this

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/millimolar.jsonld
> +    "mol/m^3"
I would delete this

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/millimolar.jsonld
> +    "10^-3 mol/L",
this should be `mmol/l` or `mmol/L`

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/millimolar.jsonld
> +    "mol/m^3"
this should be `mmol*m⁻³` or `mmol/m³`

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/degreeCelsius.jsonld
> +  "synonym": null
°C

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/degree.jsonld
> +  "synonym": null
`deg`
`°`

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/micromolar.jsonld
> +    "10^-6 mol/L",
better `µmol/L`

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/micromolar.jsonld
> +    "10^-3 mol/m^3"
better `µmol/m³` or `µmol*m⁻³`

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/molar.jsonld
> +    "10^3 mol/m^3"
this is wrong, should be `mol/m³` or `mol*m⁻³`

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/molar.jsonld
> +    "mol/L",
also `mol/l`

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/nanomolar.jsonld
> +    "10^-9 mol/L",
see comment above

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/nanomolar.jsonld
> +    "10^-6 mol/m^3"
see comments above

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/percent.jsonld
> +  "synonym": null
`%`

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/percent.jsonld
> +  "synonym": null
`percentage`

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/percent.jsonld
> +  "synonym": null
`pct` and `pc`

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/volumePerVolumePercentage.jsonld
> +    "% v/v"
```
percent v/v
v/v percent
v/v percent
volume percent
v/v %
```

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/weightPerVolumePercentage.jsonld
> +    "% w/v"
cf. comments above 
AND
w => should be g
v => should be ml
[as far as I saw]

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/volumePerVolumePercentage.jsonld
> +    "% v/v"
volumes should have same unit

2022-03-04 09:11 UTC, lzehl commented on instances/unitOfMeasurement/weightPerWeightPercentage.jsonld
> +    "% w/w"
cf. comments above
weight should have same unit

2022-03-04 09:44 UTC, MaaikevS commented
@lzehl Your requested changes are incorporated

2022-03-18 07:49 UTC, lzehl approved these changes
@MaaikevS thanks a lot. I've only made some corrections for the definitions and synonyms.

2022-03-18 07:50 UTC, merged