Added weightedCorrelationNetworkAnalysis.json
HumanBrainProject/openMINDS_controlledTerms pull request #142
Opened 2022-03-04 08:44 UTC by MaaikevS

Related to #139

2022-03-04 09:12 UTC, lzehl requested changes

2022-03-04 09:12 UTC, lzehl commented on instances/technique/weightedCorrelationNetworkAnalysis.json
> +  "@id": "https://openminds.ebrains.eu/instances/technique/WeightedCorrelationNetworkAnalysis",
`.../weightedCorrelationNetworkAnalysis`

2022-06-07 14:18 UTC, MaaikevS commented
@lzehl I see now that this PR was never merged (but apparently I closed it). Would you be able to merge it?

2022-06-07 14:23 UTC, lzehl commented
@MaaikevS could you have a look at the editions I made. If you confirm I would merge the PR

2022-06-07 14:28 UTC, MaaikevS commented
Yup, I am happy with the edits. Thanks!

2022-06-07 14:31 UTC, merged

2022-06-07 14:31 UTC, lzehl commented
@MaaikevS and merged :) thank you!