Add some commonly used electrical units
HumanBrainProject/openMINDS_controlledTerms pull request #154
Opened 2022-03-16 15:39 UTC by apdavison

plus degree and radian

2022-03-16 17:35 UTC, lzehl commented
@apdavison can you compare the degree  / radian part please with the one from @MaaikevS PR #140 ? You two can decide who should delete / merge with the other. For degree: should be arcDegree (?) so that it does not collide with temprature degreeCelcius etc. OR move over to:
"degree" -> angle in deg (°)
"radian" -> angle in radian (rad)
"celcius" -> degree in celcius (°C)
"fahrenheit" -> degree in fahrenheit (°F) 
etc ???

2022-03-16 17:46 UTC, apdavison commented
To make things simple I've removed degree and radian from this PR.

2022-03-18 07:55 UTC, lzehl requested changes
@apdavison thank you for this PR. Everything is good except that there is an empty line missing at the end of each JSONLD. Could you add this? (note: if you generate JSONs via Python you actively need to set this empty line. unfortunately Python does not follow the convention automatically.)

2022-03-18 10:38 UTC, lzehl approved these changes

2022-03-18 10:38 UTC, merged