Koehnen ftp
HumanBrainProject/openMINDS_controlledTerms pull request #169
Opened 2022-04-05 11:28 UTC by skoehnen

2022-04-05 16:04 UTC, lzehl requested changes
besides the definition (please modify correct my suggestion) this looks good

2022-04-05 16:04 UTC, lzehl commented on instances/fileRepositoryType/ftp.jsonld
> +  "definition": "FTP, the file transfer protocol, is a standard internet communication protocol which allows the transfer of files between clients and a server.",
this should be the definition of an FTP repository not the FTP itself. something in the direction of (feel free to optimize): "An 'FTP repository' is located on a server that uses file transfer protocol (FTP), a standard ..."

2022-04-12 19:15 UTC, skoehnen commented
Yes, that makes sense.
I will update definition.

2022-04-12 19:18 UTC, skoehnen commented on instances/fileRepositoryType/ftp.jsonld
> +  "definition": "FTP, the file transfer protocol, is a standard internet communication protocol which allows the transfer of files between clients and a server.",
Yes, that makes sense.
I will update definition.

2022-04-13 07:41 UTC, lzehl approved these changes

2022-04-13 07:42 UTC, merged