Follow naming conventions in id
HumanBrainProject/openMINDS_controlledTerms pull request #18
Opened 2020-12-15 07:02 UTC by olinux

Renaming wild_type to wildType for the id to follow the naming conventions -> fix for #15

2021-01-18 16:52 UTC, lzehl commented
@UlrikeS91 : I agree with Oli's suggestion (cf. also #15) Do you agree? if yes please feel free to merge.

2021-01-19 10:17 UTC, UlrikeS91 commented
@olinux and @lzehl, shouldn't the file name also be renamed to "wildType" then?

2021-01-19 12:01 UTC, lzehl commented
@UlrikeS91 no, the entries for the "name" property stays at it is usually written. the ID and the type have conventions:
- ID: lowerCamelCase
- type: UpperCamelCase
Which is true for spaces, but only question here is what to do with dashes in names? Should they remain in the ID and type?
@olinux what do you think?

2021-01-19 13:00 UTC, olinux commented
I think dashes should be generally avoided if anyhow possible. Otherwise, I would suggest to treat them just as other "filling" characters and therefore treat them as if they would be a space... meaning "foo-bar" becomes "fooBar"

2021-01-19 13:12 UTC, lzehl commented
@olinux okay. we can follow this convention. For this PR : @UlrikeS91 is right, but I misunderstood her. Could you change the filename of this json-ld also to "wildType.jsonld" ?

2021-02-16 12:04 UTC, lzehl requested changes

2021-02-16 12:04 UTC, lzehl commented on terminologies/phenotype/wild_type.jsonld
>    "name": "wild type",
I've checked again. It's completely valid to use the notation "wildtype"
@olinux again, not your mistake but could you fix it ? and change the at_id as well?

2021-02-16 12:04 UTC, lzehl commented on terminologies/phenotype/wild_type.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/phenotype/wildType",
see below (it's okay to use "wildtype" notation)

2021-02-24 13:47 UTC, merged