Updating software-related terminologies
HumanBrainProject/openMINDS_controlledTerms pull request #19
Opened 2020-12-23 11:02 UTC by jagru20

- Added schemas for a few more terms.
- Added Links to ontology for existing Terms where possible.

2021-01-18 17:06 UTC, lzehl requested changes
@jagru20 thanks a lot for updating / extending the software parts in the controlledTerms. It's highly appreciated :slightly_smiling_face: 

A general feedback point: please check again all "names" in your changes. The entries here should be with space and everything. The lowerCamelCase convention needs to be only followed for the properties, and the UpperCamelCase convention for the types. But the values can / should be written normally.

Please, see also my comment for the support.json-ld

2021-01-18 17:06 UTC, lzehl commented on terminologies/contributionType/softwareSupport.jsonld
>    "description": "Contributing by providing support to users of the product.",
If you rename it to softwareSupport the description needs to be specific as well. And we need to introduce other specific support contribution as well (e.g., technicalSupport, scientificSupport?, etc).

2021-02-16 11:53 UTC, lzehl requested changes
@jagru20 I think there was a misunderstanding between us for the "name" entries. They do not need to use lowerCamelCase or UpperCamelCase, but they should be written in lower capitals except for abbreviations (e.g. HPC; although abbreviations should only be used in "name" if they are more commonly known than the full name) and given names (e.g., Java). Could you update this accordingly?

Otherwise this PR looks good.

2021-02-16 11:55 UTC, jagru20 commented
> 
> 
> @jagru20 I think there was a misunderstanding between us for the "name" entries. They do not need to use lowerCamelCase or UpperCamelCase, but they should be written in lower capitals except for abbreviations (e.g. HPC; although abbreviations should only be used in "name" if they are more commonly known than the full name) and given names (e.g., Java). Could you update this accordingly?
> 
> Otherwise this PR looks good.

Yes, I got that wrong then. I will update that.

2021-02-16 11:57 UTC, lzehl commented
@jagru20 top :) thanks a lot!

2021-02-26 13:17 UTC, lzehl approved these changes

2021-02-26 13:18 UTC, merged