Add technique Ensemble Learning Bagging
HumanBrainProject/openMINDS_controlledTerms pull request #217
Opened 2022-04-29 11:10 UTC by skoehnen

2022-04-29 11:13 UTC, skoehnen commented
Addresses issue #215

2022-04-29 11:20 UTC, lzehl commented on instances/technique/ensembleLearningBagging.jsonld
> +  "definition": "'Ensemble learning bagging' is a specialized ensemble learning technique, a group of 'weak-learner' methods that get trained in parallel on random data-points of the training-dataset
@skoehnen I did some minor changes. please let me know if they fit.

2022-04-29 11:27 UTC, skoehnen commented on instances/technique/ensembleLearningBagging.jsonld
> +  "definition": "'Ensemble learning bagging' is a specialized ensemble learning technique, a group of 'weak-learner' methods that get trained in parallel on random data-points of the training-dataset
Now it sounds like the "Ensemble learning bagging" is the group of "weak-learner methods".
But it is the whole Framework from training, using and aggregation of results.

2022-04-29 12:51 UTC, lzehl requested changes

2022-04-29 12:51 UTC, lzehl commented on instances/technique/ensembleLearningBagging.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/technique/EnsembleLearningBagging",
this should be .../ensembleLearningBagging

2022-04-29 12:51 UTC, lzehl commented on instances/technique/ensembleLearningBagging.jsonld
> +  "definition": "'Ensemble Learning Bagging' is a specialized Ensemble Learning technique, a framework that uses a group of 'weak-learner' methods, which get trained in parallel on random data-points
This should be "'Ensemble learning bagging' is a specialized ensemble learning technique,...

2022-04-29 12:51 UTC, lzehl commented on instances/technique/ensembleLearningBagging.jsonld
> +  "name": "Ensemble Learning Bagging",
this should be "ensemble learning bagging"

2023-01-16 08:53 UTC, lzehl commented on instances/technique/bootstrapAggregating.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/technique/bootstrapAggregating",
@skoehnen I still have an issue with this term... It sounds incomplete (although I know that this term is used that way). Would it be incorrect to call it "bootstrap aggregation" or "bootstrap aggregating analysis" or just "bagging" ?

2024-05-07 10:10 UTC, UlrikeS91 commented
Replace by new PR https://github.com/openMetadataInitiative/openMINDS_instances/pull/79 in instances-repo

2024-05-07 10:10 UTC, closed without merging