Add PanProject techniques
HumanBrainProject/openMINDS_controlledTerms pull request #22
Opened 2021-02-16 13:05 UTC by UlrikeS91

Here the updated JSON-LDs based on a lot of feedback from the previous PR #12.

2021-02-26 15:36 UTC, lzehl requested changes
@UlrikeS91 as discussed ignore change request for now

2021-02-26 15:36 UTC, lzehl commented on terminologies/technique/3DMorphologicalReconstruction.jsonld
> +{
Based on the last ontology discussion this one is deprecated and should be now covered in reconstructionTechnique, correct?

2021-02-26 15:36 UTC, lzehl commented on terminologies/technique/SodiumDodecylSulfateDigestedFreezeFractureReplicaLabeling.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/SodiumDodecylSulfateDigestedFreezeFractureReplicaLabeling",
Is the full name typically used or is it the abbreviation? If the first is true, leave it like it is, if the second one is true we may consider the abbreviated format.

2021-02-26 15:36 UTC, lzehl commented on terminologies/technique/cellAttachedPatchClampElectrophysiology.jsonld
> +  "name": "cell-attached patch clamp electrophysiology",
I don't remember but I think that's what we decided now, correct?

2021-02-26 15:36 UTC, lzehl commented on terminologies/technique/extracellularElectrophysiology.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/extracellularElectrophysiology",
I would actually vote to through this out because it is too general. I would like to know at least if its single electrode, or multi-electrode electrophysiology, no? And the we have EEG and iEEG and all the other EEGs, and I guess ECoG. I do not think a general extracellular electrophysiology technique is necessary...

Also at @tgbugs what do you think?

2021-02-26 15:36 UTC, lzehl commented on terminologies/technique/hierarchicalClustering.jsonld
> +  "name": "hierarchical clustering",
same here as for "extracellular electrophysiology". I would kick this out because it is too general. I would rather register more hierarchical clustering techniques (e.g. Ward, K-means etc), no?

@tgbugs what do you think?

2021-02-26 15:36 UTC, lzehl commented on terminologies/technique/highDensityElectroencephalography.jsonld
> +  "name": "high-density electroencephalography",
didn't we kick this one out because we said it's a hardware think?

2021-02-26 15:36 UTC, lzehl commented on terminologies/technique/highFieldFunctionalMagneticResonanceImaging.jsonld
> +  "name": "high-field functional magnetic resonance imaging",
didn't we kick this one out because we said it's a hardware think?

2021-02-26 15:36 UTC, lzehl commented on terminologies/technique/iontophoresisTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/iontophoresisTechnique",
kill Technique (not needed here)

2021-03-23 15:27 UTC, UlrikeS91 commented
Outdated and replaced by #34

2021-03-23 15:27 UTC, closed without merging