chemical mixture type
HumanBrainProject/openMINDS_controlledTerms pull request #238
Opened 2022-06-02 14:08 UTC by Peyman-N

2022-06-02 14:31 UTC, apdavison requested changes

2022-06-02 14:31 UTC, apdavison commented on instances/chemicalMixtureType/colloid.jsonld
> +    "description": "A colloid is a mixture where very small particles of one substance are evenly distributed throughout another substance. They appear very similar to solutions, but the particles ar
some cases of multiple       spaces between words here should be      fixed

2022-06-02 14:31 UTC, apdavison commented on instances/chemicalMixtureType/colloid.jsonld
> +}
need newline at the end of all files to make them valid JSON

2022-06-02 14:32 UTC, apdavison commented on instances/chemicalMixtureType/colloid.jsonld
> +    "description": "A colloid is a mixture where very small particles of one substance are evenly distributed throughout another substance. They appear very similar to solutions, but the particles ar
`a . . . . colloid`, `of . . . . time`

2022-06-02 14:44 UTC, Peyman-N commented on instances/chemicalMixtureType/colloid.jsonld
> +}
My VS code keeps deleting them, would add it with github editor.

2022-06-02 17:46 UTC, apdavison approved these changes

2022-07-20 08:16 UTC, UlrikeS91 requested changes
The instances and the schema look fine to me, but you are missing the corresponding instance that should be added to the terminology folder, here: https://github.com/HumanBrainProject/openMINDS_controlledTerms/tree/v1/instances/terminology.

2022-09-05 15:44 UTC, lzehl approved these changes
@Peyman-N and @UlrikeS91 I've made some changes to the definitions and descriptions. Please double check the changes and if you are okay with them let me know. From my side this PR is good to be merged then.

2022-09-06 07:33 UTC, UlrikeS91 approved these changes

2022-09-06 07:33 UTC, merged