new technique: Golgi staining
HumanBrainProject/openMINDS_controlledTerms pull request #256
Opened 2022-07-20 11:25 UTC by UlrikeS91

2022-07-20 11:37 UTC, lzehl requested changes

2022-07-20 11:37 UTC, lzehl commented on instances/technique/golgiStaining.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/technique/golgiStaining",
this should be capitalized (.../GolgiStaining)since Golgi is a proper name.

2022-07-20 11:37 UTC, lzehl commented on instances/technique/golgiStaining.jsonld
> +  "definition": "Any of several methods for staining nerve cells, nerve fibers, and neuroglia in which fixed tissue is impregnated with silver nitrate and potassium dichromate resulting in the comple
I would change this a bit (even though this is the definition on interlex).

"'Golgi staining' includes several silver staining techniques in which fixed tissue is impregnated with silver nitrate and potassium dichromate resulting in the complete staining of some nerve cells while other cells are not stained at all." with referencing original interlex source and wikipedia

2022-07-20 11:37 UTC, lzehl commented on instances/technique/golgiStaining.jsonld
> +  "synonym": null
Golgi method
black reaction
?

2022-07-20 11:49 UTC, UlrikeS91 commented on instances/technique/golgiStaining.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/technique/golgiStaining",
true, fixed

2022-07-20 11:50 UTC, UlrikeS91 commented on instances/technique/golgiStaining.jsonld
> +  "definition": "Any of several methods for staining nerve cells, nerve fibers, and neuroglia in which fixed tissue is impregnated with silver nitrate and potassium dichromate resulting in the comple
referenced interlex and not wikipedia, because I didn't use it (only interlex)

2022-07-20 11:50 UTC, UlrikeS91 commented on instances/technique/golgiStaining.jsonld
> +  "synonym": null
added

2022-07-21 12:57 UTC, lzehl approved these changes

2022-07-21 12:58 UTC, merged