MRI technique updates
HumanBrainProject/openMINDS_controlledTerms pull request #262
Opened 2022-08-19 10:34 UTC by UlrikeS91

related to #212 

I started preparing the points from [this comment](https://github.com/HumanBrainProject/openMINDS_controlledTerms/issues/212#issuecomment-1189994659). I struggled with the definitions for the new sequence techniques, so any help would be appreciated @lzehl and @tgbugs.

We can only start the cleanup, when the new techniques can be used in the KG.

2022-08-22 09:04 UTC, apdavison commented
@Peyman-N do you have any comments here, given your background in MRI and your work on an openMINDS/MRI extension?

2022-09-05 16:08 UTC, lzehl requested changes
@UlrikeS91 thanks for preparing this. 

I think we don't need to use "... technique" here. Just go with the "xxx sequence".
I'll prepare a summary in separate comment (in the related issue).

2022-09-06 10:48 UTC, UlrikeS91 commented
Updated instances based on the comments in the issue #212

2022-09-06 10:57 UTC, lzehl approved these changes

2022-09-06 11:00 UTC, merged