Receptive fields and retinotopic mapping
HumanBrainProject/openMINDS_controlledTerms pull request #263
Opened 2022-08-19 11:06 UTC by UlrikeS91

related to #227 

I'm not sure my definitions are 100% accurate but this is what I could find out about the techniques. One major note is that RF mapping can be performed for other sensory areas as well - not only for visual RFs. 

@tgbugs and @lzehl

2022-08-22 12:34 UTC, lzehl requested changes
@tgbugs we need your help with the definitions :)

2022-08-22 12:34 UTC, lzehl commented on instances/technique/receptiveFieldMapping.jsonld
> +  "definition": "'Receptive field mapping' is use to map out which portion of sensory space elicit neuronal responses when stimulated.",
**Alternative definition:**  "'Receptive field mapping' is a stimulation technique used to map out which neuron or neuron population preferably elicit a neuronal response to a specific sensory stimulus or sensory stimulus set." 

@tgbugs I think we need your additional feedback here for a nice definition.

2022-08-22 12:34 UTC, lzehl commented on instances/technique/retinotopicMapping.jsonld
> +  "definition": "'Retinotopic mapping' is a special type of receptive field mapping where the visual receptive field position is mapped in retinotopic coorinates in a brain region.",
Better definition: "'Retinotopic mapping' is a stimulation technique in which neurons or neuron populations within the visual stream are mapped point-to-point to visual input of the retinal surface.

@tgbugs also here I think we need you feedback for a nice definition.

2022-09-05 16:04 UTC, lzehl commented
@UlrikeS91 I've made some changes in the definitions. Please double check. If you are okay with the changes I suggest we merge this one. Corrections of the definitions by @tgbugs can be integrated later (if necessary).

2022-09-06 07:38 UTC, UlrikeS91 reviewed
I did a very minor update to the definition of the RF mapping (a "to" was missing) and added "RF mapping" as synonym. 

I can't approve my own PR (therefore I only comment). But I think the changes are good and we can merge now.

2022-09-06 07:46 UTC, lzehl approved these changes

2022-09-06 07:46 UTC, merged