Issue 292 body system
HumanBrainProject/openMINDS_controlledTerms pull request #306
Opened 2022-09-14 17:13 UTC by ehennestad

2022-09-23 08:51 UTC, UlrikeS91 requested changes

2022-09-23 08:51 UTC, UlrikeS91 commented on instances/bodySystem/cardiovascularSystem.jsonld
> +  "definition": "'Cardiovascular system' is an anatomical system that has as its parts the heart and blood vessels.",
"'The 'cardiovascular system' is an anatomical organ system where the heart pumps blood through blood vessels to and from all part of the body."

2022-09-23 08:51 UTC, UlrikeS91 commented on instances/bodySystem/centralNervousSystem.jsonld
> +  "description": "The central nervous system is the core nervous system that serves an integrating and coordinating function.",
Better to flip them around:

definition: "The 'central nervous system' is the main processing center in most organisms. It's function is to take in sensory information, process information, and send out motor signals."

description: "In vertebrates, the central nervous system (CNS) consists of the brain and the spinal cord. In invertebrates, it includes the central ganglia and the nerve cord."

2022-09-23 08:51 UTC, UlrikeS91 commented on instances/bodySystem/digestiveSystem.jsonld
> +  "definition": "'Digestive system' is an anatomical system that has as its parts the organs devoted to the ingestion, digestion, and assimilation of food and the discharge of residual wastes.",
"The 'digestive system' is an anatomical organ system is composed of organs devoted to the ingestion, digestion, the assimilation of food and the discharge of residual wastes."

2022-09-23 08:51 UTC, UlrikeS91 commented on instances/bodySystem/musculoskeletalSystem.jsonld
> +  "description": "Anatomical system that consists of the muscular and skeletal systems.",
definition: "The 'musculoskeletal system' is an anatomical organ system composed of organs providing the body with movement, stability, shape and support."

description: "The musculoskeletal system (sometimes also called locomotor system) is subdivided into two broader systems, the skeletal system and the muscular system. The skeletal system includes bones and joints. The muscular system includes all muscles in the body."

2022-09-23 08:51 UTC, UlrikeS91 commented on instances/bodySystem/vascularSystem.jsonld
> +  "definition": "'Vascular system' is an anatomical system that consists of all blood and lymph vessels.",
"The 'vascular system' is an anatomical organ system that consists of all vessels in the body, and carries blood and lymph through all parts of the body."

2022-09-23 08:52 UTC, UlrikeS91 commented
As a general note, we always prioritize the definition over the description and the definition should be as short as possible (pref. only one single sentence).

2022-09-27 13:54 UTC, ehennestad commented
Great suggestions Ulrike. I made the changes in this commit 92e4bfdf9a9f19351b4ea396f20d59dd0fd5bdab

2023-01-20 08:46 UTC, UlrikeS91 requested changes

2023-01-20 08:46 UTC, UlrikeS91 commented on instances/bodySystem/centralNervousSystem.jsonld
> +  "definition": "The 'central nervous system' is the main processing center in most organisms. It's function is to take in sensory information, process information, and send out motor signals.",
"Its function..." (without the ')

2023-01-20 08:46 UTC, UlrikeS91 commented on instances/bodySystem/digestiveSystem.jsonld
> +  "definition": "The 'digestive system' is an anatomical organ system is composed of organs devoted to the ingestion, digestion, the assimilation of food and the discharge of residual wastes.",
"The 'digestive system' is an anatomical organ system composed..." (not "system IS composed")

2023-01-31 10:16 UTC, merged

2023-01-31 18:25 UTC, lzehl commented
For consistency we should probably redo this one and change the Schema to OrganismSystem (to match OrganismSubstance; which is also not fixed yet)