Update with PanProject techniques
HumanBrainProject/openMINDS_controlledTerms pull request #34
Opened 2021-03-23 15:26 UTC by UlrikeS91

This PR replaces the old one #22.

These techniques have been updated based on the changed discussed during the latest meetings. A few minor additional changes may be done following our meeting tonight (3 techniques only). 

@lzehl: 
1. Ignore the SDS-FRL technique. Marked for tonight. May change. 
2. Check for useless "technique" mentioned in the LDs. As discussed with @tgbugs, we can remove "[...] technique" from the name whenever the rest makes sense on its own (e.g. "secondary antibody staining (technique)" but not "reconstruction technique"). 
3. There is a bunch of high-level techniques. We decided to keep those but to make curators aware that these should not (ever) be used.

2021-03-23 16:43 UTC, lzehl requested changes
we should involve @tgbugs for the question on where "technique" is needed

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/activityModulationTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/activityModulationTechnique",
"technique" can be removed here

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/anaesthesiaAdministrationTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/anaesthesiaAdministrationTechnique",
"technique" can be removed here

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/anaesthesiaMonitoringTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/anaesthesiaMonitoringTechnique",
"technique" can be removed here

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/anaesthesiaTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/anaesthesiaTechnique",
"technique" can be removed here

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/anatomicalDelineationTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/anatomicalDelineationTechnique",
"technique" can be removed here

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/anatomicalParcellationTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/anatomicalParcellationTechnique",
"technique" can be removed here

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/anatomicalSegmentationTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/anatomicalSegmentationTechnique",
"technique" can be removed here

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/cellAttachedPatchTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/cellAttachedPatchTechnique",
To clarify: patch or patch clamp ?

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/contrastEnhancementTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/contrastEnhancementTechnique",
"technique" can be removed here

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/currentClampTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/currentClampTechnique",
"technique" can be removed here

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/deepLearning.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/deepLearning",
To clarify: maybe better "deep learning algorithm" ?

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/densityMeasurementTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/densityMeasurementTechnique",
"technique" can be removed here

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/epiduralElectroencephalography.jsonld
> +  "name": "epidural electroencephalography",
This one I'd like to check/discuss. As far as I know this is an ECoG which can be epidural or subdural. So I guess it would be more accurate to differentiate there (epidural ECoG vs subdural ECoG).

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/generalLinearModellingTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/generalLinearModellingTechnique",
"technique" can be removed here

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/averageLinkageHierarchicalClustering.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/averageLinkageHierarchicalClustering",
for consistency and how it is usually used this should be just "average linkage clustering" (which is a clustering technique of the technique class hierarchical agglomerative clustering)

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/lightSheetMicroscopy.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/lightSheetMicroscopy",
it appears to me that the term "light-sheet fluorescence microscopy" is more used. And I've learned that this is also referred to as "single plane illumination microscopy", or "orthogonal plane fluorescence optical sectioning microscopy". Each are actually different techniques with different resolutions. At least that's what I've found

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/dualViewInvertedSelectivePlaneIlluminationMicroscopy.jsonld
> +  "name": "dual view inverted selective plane illumination microscopy",
dual-view

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/literatureMinning.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/literatureMinning",
"literatureMining" not minning; is a consistent typo and needs to be corrected in several places in the schema

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/maximumProbabilityProjectionTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/maximumProbabilityProjectionTechnique",
"technique" can be removed (I think)

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/metaAnalysisTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/metaAnalysisTechnique",
"technique" can be removed

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/patchClampTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/patchClampTechnique",
"technique" can be removed

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/photonStimulationTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/photonStimulationTechnique",
I'm confused here: is this something else than photoactivation ??

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/probabilisticAnatomicalParcellationTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/probabilisticAnatomicalParcellationTechnique",
"technique" can be removed (I think).

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/quantificationTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/quantificationTechnique",
"technique" can be removed (I think)

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/reconstructionTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/reconstructionTechnique",
"technique" can be removed (I think)

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/restingStateFunctionalMagneticResonanceImaging.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/restingStateFunctionalMagneticResonanceImaging",
I'm still against this one :sweat_smile:

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/spatialRegistration.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/spatialRegistration",
we should also provide the more specific variations. that one should be tasked to Timo

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/spatialTransformation.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/spatialTransformation",
we should also provide the more specific variations. that one should be tasked to Timo

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/stereotacticElectroencephalography.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/stereotacticElectroencephalography",
note: apparently this is now also known as "stereoelectroencephalography"

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/tissueClearingTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/tissueClearingTechnique",
"technique" can be removed (I think)

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/ultraHighFieldFunctionalMagneticResonanceImaging.jsonld
> +  "name": "ultra-high field functional magnetic resonance imaging",
"ultra high-field functional magnetic resonance imaging"

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/voltageClampTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/voltageClampTechnique",
"technique" can be removed (I think)

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/wholeCellPatchClampTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/wholeCellPatchClampTechnique",
"technique" can be removed (I think)

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/wideFieldFluorescenceMicroscopy.jsonld
> +  "name": "wide field fluorescence microscopy",
"widefield fluorescence microscopy" or "wide-field fluorescence microscopy"

2021-03-23 16:43 UTC, lzehl commented on terminologies/technique/wideFieldMicroscopy.jsonld
> +  "name": "wide field microscopy",
"widefield microscopy" or "wide-field microscopy"

2021-03-24 10:51 UTC, lzehl commented
@UlrikeS91 I forgot that this was still open. We can wait for @tgbugs to comments here. After we have all feedback, could you move the PR to the openMINDS_instances?

2021-03-24 11:07 UTC, UlrikeS91 commented
Yeah, can do that.

2021-04-06 17:14 UTC, tgbugs commented on terminologies/technique/anaesthesiaTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/anaesthesiaTechnique",
Keep technique.

2021-04-06 17:14 UTC, tgbugs commented on terminologies/technique/activityModulationTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/activityModulationTechnique",
Keep technique.

2021-04-06 17:15 UTC, tgbugs commented on terminologies/technique/anatomicalDelineationTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/anatomicalDelineationTechnique",
Keep technique.

2021-04-06 17:15 UTC, tgbugs commented on terminologies/technique/anatomicalParcellationTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/anatomicalParcellationTechnique",
Keep technique.

2021-04-06 17:15 UTC, tgbugs commented on terminologies/technique/anatomicalSegmentationTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/anatomicalSegmentationTechnique",
Keep technique.

2021-04-06 17:20 UTC, tgbugs commented
Actually, on further review, I think it is ok to zap `Technique` from the end of all of these because you have `/technique/` in the url as well, so it is clear. It should be retained in the label though.

2021-04-09 13:50 UTC, lzehl commented on terminologies/technique/epiduralElectroencephalography.jsonld
> +  "name": "epidural electroencephalography",
@tgbugs : what do you think here?

2021-04-09 14:06 UTC, lzehl commented on terminologies/technique/photonStimulationTechnique.jsonld
> +  "@id": "https://openminds.ebrains.eu/controlledTerms/technique/photonStimulationTechnique",
@tgbugs what is the difference?

2021-04-09 15:59 UTC, lzehl commented
I've updated the techniques according to this PR now on openMINDS_instances and will therefore close this PR here now.
@tgbugs : thank you for your feedback. The ontological identifiers for the techniques can be added to the openMINDS_instances when they are ready.
@UlrikeS91 : a big thank you for preparing this PR!

2021-04-09 15:59 UTC, closed without merging