Create alphaActivity.jsonld
HumanBrainProject/openMINDS_controlledTerms pull request #434
Opened 2023-06-30 09:19 UTC by aeidi89

#258

2023-08-18 10:02 UTC, lzehl requested changes

2023-08-18 10:02 UTC, lzehl commented on instances/measuredSignalType/alphaActivity.jsonld
> +  "synonym": [
please remove the capitalization (I know they appear as such in interlex but openMINDS tries to avoid capitalization for terms when they are not intentional (e.g. for names or abbreviations))

2023-08-18 10:02 UTC, lzehl commented on instances/measuredSignalType/alphaActivity.jsonld
> +  "definition": "Alpha activity is an electromagnetic oscillation in the frequency range of 8–12 Hz arising from synchronous and coherent (in phase / constructive) electrical activity. [adapted from
I rather suggest the following:

"Alpha activity is a neural oscillation in the low frequency range (typically between 8-12 Hz) arising from synchronous and coherent electrical activity in the brain. [adapted from [wikipedia](https://en.wikipedia.org/wiki/Alpha_wave)]"

@apdavison would you agree with this definition?

2024-05-07 11:08 UTC, UlrikeS91 commented
Replaced by https://github.com/openMetadataInitiative/openMINDS_instances/pull/84

2024-05-07 11:08 UTC, closed without merging