Create gammaActivity.jsonld
HumanBrainProject/openMINDS_controlledTerms pull request #435
Opened 2023-06-30 11:02 UTC by aeidi89

#258

2023-08-18 10:07 UTC, lzehl requested changes

2023-08-18 10:07 UTC, lzehl commented on instances/measuredSignalType/gammaActivity.jsonld
> +  "synonym": [
please remove the capitalization

2023-08-18 10:07 UTC, lzehl commented on instances/measuredSignalType/gammaActivity.jsonld
> +  "definition": "Gamma activiation is an electromagnetic oscillation in the frequency range of 25 to 100 Hz (40 Hz is prototypical). [adapted from [wikipedia](https://en.wikipedia.org/wiki/Gamma_wave
"Gamma activity is a neural oscillation in the high frequency range (typically between 30-150 Hz) arising from synchronous and coherent electrical activity in the brain. [adapted from [wikipedia](https://en.wikipedia.org/wiki/Gamma_wave)]"

@apdavison would you agree with this definition?

2024-05-07 11:09 UTC, UlrikeS91 commented
Replaced by https://github.com/openMetadataInitiative/openMINDS_instances/pull/84

2024-05-07 11:09 UTC, closed without merging