Create betaActivity.jsonld
HumanBrainProject/openMINDS_controlledTerms pull request #436
Opened 2023-06-30 11:03 UTC by aeidi89

#258

2023-08-18 10:10 UTC, lzehl requested changes

2023-08-18 10:10 UTC, lzehl commented on instances/measuredSignalType/betaActivity.jsonld
> +    "Beta wave"
comma is missing (thats why the checks fail). please correct

2023-08-18 10:10 UTC, lzehl commented on instances/measuredSignalType/betaActivity.jsonld
> +  "synonym": [
please remove the capitalizations

2023-08-18 10:10 UTC, lzehl commented on instances/measuredSignalType/betaActivity.jsonld
> +  "definition": "Beta activity is an electromagnetic oscillation in the frequency range of 8–12 Hz arising from synchronous and coherent (in phase / constructive) electrical activity. [adapted from [
"Beta activity is a neural oscillation in the mid frequency range (typically between 12-30 Hz) arising from synchronous and coherent electrical activity in the brain. [adapted from [wikipedia](https://en.wikipedia.org/wiki/Beta_wave)]"

@apdavison would you agree with this definition?

2024-05-07 11:09 UTC, UlrikeS91 commented
Replaced by https://github.com/openMetadataInitiative/openMINDS_instances/pull/84

2024-05-07 11:09 UTC, closed without merging