Molecular Entities needed for in depth
HumanBrainProject/openMINDS_controlledTerms pull request #458
Opened 2023-11-17 15:57 UTC by Peyman-N

2023-11-25 09:56 UTC, lzehl requested changes
@Peyman-N thank you for this PR. I know that adding these entities is urgent but I would like to establish some conventions for adding chemical entities.

I would suggest the following:
+ name: use the IUPAC nomenclature
+ atID suffix: use the IUPAC name
+ filename: use the IUPAC name
+ definition: always cite your source; do not list synonyms here; I would always include here though the molecular formula
+ description: always cite your source; do not list synonyms here
+ preferredOntologyID: do not use pubchem (for what I can see this is not an ontology); use ChEBI instead
+ synonyms: only use exact synonyms; list alphabetically

Please let me know if you would discuss this suggestions or, when you agree with them, need help updating this PR.

2023-11-25 09:56 UTC, lzehl commented on instances/molecularEntity/2-Bromo-2-chloro-1,1,1-trifluoroethane.jsonld
> +  "definition": "2-Bromo-2-chloro-1,1,1-trifluoroethane is a nonflammable, halogenated, hydrocarbon anesthetic that provides relatively rapid induction with little or no excitement. ",
please delete the unnecessary space at the end of the definition and add the source of the definition (e.g. as citation and/or link to the source)

2023-11-25 09:56 UTC, lzehl commented on instances/molecularEntity/2-Bromo-2-chloro-1,1,1-trifluoroethane.jsonld
> +  "synonym": []
if there are no synonyms this should be null.

2023-11-25 09:56 UTC, lzehl commented on instances/molecularEntity/DNQX.jsonld
> +  "@id": "https://openminds.ebrains.eu/instances/molecularEntity/DNQX",
please follow one convention for chemical entities: I would suggest we always use the IUPAC  name.

2023-11-25 09:56 UTC, lzehl commented on instances/molecularEntity/DNQX.jsonld
> +  "definition": "DNQX (6,7-dinitroquinoxaline-2,3-dione) is a competitive antagonist at AMPA and kainate receptors, two ionotropic glutamate receptor (iGluR) subfamilies.",
Please add the source of the definition. Adapt according to the decision made for the naming convention. Do never list synonyms in the definition. We should always just list them under "synonym".

2023-11-25 09:56 UTC, lzehl commented on instances/molecularEntity/DNQX.jsonld
> +  "description": "It is used in a variety of molecular biology subfields, notably neurophysiology, to assist researchers in determining the properties of various types of ion channels and their poten
Please add the source of the description. Please adapt so that the description can be read without the definition.

2023-11-25 09:56 UTC, lzehl commented on instances/molecularEntity/DNQX.jsonld
> +  "definition": "DNQX (6,7-dinitroquinoxaline-2,3-dione) is a competitive antagonist at AMPA and kainate receptors, two ionotropic glutamate receptor (iGluR) subfamilies.",
I would also delete the further information on the receptors which is irrelevant for this entity. I would though add it's antagonistic competitors for the receptors (and or clearly identify which binding site it uses).

2023-11-25 09:56 UTC, lzehl commented on instances/molecularEntity/DNQX.jsonld
> +  "name": "DNQX",
see naming conventions suggestion: IUPAC Name

2023-11-25 09:56 UTC, lzehl commented on instances/molecularEntity/DNQX.jsonld
> +  "synonym": [
correct to change in naming convention

2023-11-25 09:56 UTC, lzehl commented on instances/molecularEntity/EDTA.jsonld
> +    "name": "EGTA",
wrong name. but should be anyway changed to IUPAC Name

2023-11-25 09:56 UTC, lzehl commented on instances/molecularEntity/EDTA.jsonld
> +    "definition": "Ethylenediaminetetraacetic acid (EDTA), also called edetic acid after its own abbreviation, is an aminopolycarboxylic acid with the formula [CH2N(CH2CO2H)2]2.",
source?

2023-12-18 21:10 UTC, apdavison commented
Do we really want IUPAC names in all cases? For example, "sucrose" is a much more useful name than "β-D-fructofuranosyl α-D-glucopyranoside"

2023-12-19 08:39 UTC, lzehl commented
@apdavison we need to discuss (I see the issue with IUPAC as well). However using trivial names causes issues as well because not every component has one and we end up being very inconsistent within the terminology. I would like to have something consistent as name / id and then put everything else in the synonyms

2023-12-19 09:20 UTC, apdavison commented
This is a nice comparison of the major public chemistry databases: https://doi.org/10.1002/cmdc.201700724

As a naming convention, I suggest picking one of them, let's say PubChem, since it has a better search interface than UniChem, ChemSpider is apparently not fully public, and ChEBI is missing a lot of terms.

For the first few chemicals in this PR, this would give the following (PubChem name, followed by current name in this PR in parentheses):

- halothane (2-Bromo-2-chloro-1,1,1-trifluoroethane)
- 6,7-Dinitro-1,4-dihydroquinoxaline-2,3-dione (DNQX)
- Edetic Acid (EDTA)
- Egtazic acid (EGTA)
- 4-(2-Hydroxyethyl)-1-piperazine ethanesulfonic acid (HEPES)
- Magnesium ATP (MgATP)
-

2023-12-19 10:33 UTC, lzehl commented
@apdavison thank you for doing some research to solve this. I think your suggestion is great. Let's go with PubChem. We should check if we could get in contact with them long-term (to see if we can collaborate/contribute directly)

2023-12-19 16:47 UTC, lzehl commented
@Peyman-N all updates done or are you still on it? I'm meeting with @tgbugs now and will mention our decision. Hope he agrees.

2023-12-19 17:18 UTC, lzehl commented
@Peyman-N @apdavison feedback from @tgbugs : they are using ChEBI in the ontology (NIF/InterLex) but PubChem is good as well. If terms are missing from ChEBI @tgbugs would be interested to know which terms these are. @apdavison do you have examples?

2023-12-19 17:29 UTC, apdavison commented
> do you have examples?

none to hand. This comment is based on the review article I mentioned above, and on ChEBI having less comprehensive lists of synonyms (for example, "DNQX" gives no hits in ChEBI, but if you try search for it in PubChem then use the synonyms you find there to search ChEBI you can find it).

2023-12-20 12:18 UTC, Peyman-N commented
Hello, everyone.
Sorry for the late response.

When it comes to small molecules, ChEBI is comprehensive enough for our purposes. The only small molecule that I couldn't find is [Silver ammonium](https://pubchem.ncbi.nlm.nih.gov/compound/57440423). However, for larger molecules, it becomes less extensive, especially for drugs and proteins.

Anyway, I really prefer **ChEBI** as it is more widely used by the community. On the other hand, PubChem anchors to multiple ontologies, which is nice. However, I think we should discuss the possibility of anchoring to multiple ontologies in the future.

2023-12-20 12:33 UTC, lzehl commented
@Peyman-N @apdavison  what does this mean now? you would like to connect use the ChEBI name when available and to PubChem when it is not available in ChEBI? OR do we stick to original suggestion to only use the PubChem name? (@Peyman-N connecting to multiple ontologies is handled by InterLex, I would not like to take on this task as well)

2023-12-20 13:35 UTC, Peyman-N commented
No no, sorry I didn't explain myself correctly. I mean for naming convention we would use PubChem.
I was speaking about prefer ontologie, any way the interlex and PubChem, would take care of the linkage there.

2023-12-20 14:00 UTC, lzehl commented
got it @Peyman-N thanks for clarifying!

2024-01-04 16:51 UTC, apdavison approved these changes

2024-01-04 16:51 UTC, apdavison commented
@lzehl can we merge this?

2024-01-08 09:53 UTC, lzehl commented
@apdavison yes please. one approval should be enough. We do not need to have two people approving for instances (that were discussed beforehand) and smaller issues I would say.

2024-01-08 09:53 UTC, merged

2024-01-08 10:04 UTC, apdavison commented
@lzehl I agree in general, but since this PR also has the goal of establishing conventions I think we should all approve it.

2024-01-08 10:09 UTC, lzehl commented
@apdavison as we approved / agreed on a convention in the discussion I merged it now already because I thought this one is urgent. I can go over the instances maybe some time this week in detail and do corrections if needed.