Cell types olfactory
HumanBrainProject/openMINDS_controlledTerms pull request #459
Opened 2023-11-22 14:57 UTC by Peyman-N

A forgotten pull request concerning cell types for olfactory system

2023-11-27 11:23 UTC, lzehl requested changes

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/externalTuftedCell.jsonld
> +    "definition": null,
Please always provide a one sentence definition.

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/externalTuftedCell.jsonld
> +    "synonym": null
please provide the synonyms as stated in the ontology

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/externalTuftedCell.jsonld
> +    "description": "External tufted cells have large somata and abundant cytoplasm containing stacks of Nissl material; their main dendrites are characterized by pale cytoplasm and a regular array of
please make the citation a link if possible

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/externalTuftedCell.jsonld
> +    "description": "External tufted cells have large somata and abundant cytoplasm containing stacks of Nissl material; their main dendrites are characterized by pale cytoplasm and a regular array of
please provide a full description or set to null and provide a good one sentence definition.

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/granuleCellOlfactoryBulb.jsonld
> +    "definition": "The main intrinsic neuron in the vertebrate olfactory bulb. It lacks an axon.",
Please provide this a one sentence at cite your source. Be clear if you are referring to the superclass of granule cells in the olfactory bulb or to the main or accessory granule cells.

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/granuleCellOlfactoryBulb.jsonld
> +    "definition": "The main intrinsic neuron in the vertebrate olfactory bulb. It lacks an axon.",
adapt name if you a clear about this

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/granuleCellOlfactoryBulb.jsonld
> +    "description": "Each cell gives rise to short central dendrites and a single long apical dendrite that traverses the granule cell layer, pierces the mitral cell body layer, and branches and termi
source is missing

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/externalTuftedCell.jsonld
> +    "knowledgeSpaceLink": null,
KS link is missing but does exist: https://knowledge-space.org/wiki/NIFEXT:121#olfactory-bulb-main-tufted-cell

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/granuleCellOlfactoryBulb.jsonld
> +    "knowledgeSpaceLink": null,
KS link is missing: at least for the two sub types (main or accessory) the links exist: 
https://knowledge-space.org/wiki/NLXCELL:20090401#olfactory-bulb-accessory-granule-cell
https://knowledge-space.org/wiki/NIFEXT:123#olfactory-bulb-main-granule-cell

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/granuleCellOlfactoryBulb.jsonld
> +    "synonym": null
there are synonyms for both sub types. please add them

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/externalTuftedCell.jsonld
> +    "@id": "https://openminds.ebrains.eu/instances/cellType/externalTuftedCell",
We need to investigate if we should call them external or superficial tufted cells. "Three subclasses of tufted cells are recognized based on location in the EPL: superficial, middle, and deep tufted cells (Cajal, R. S. Y., 1890; Pinching, A. J. and Powell, T. P., 1971a; Macrides, F. and Schneider, S. P., 1982; Orona, E. et al., 1984)"

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/externalTuftedCell.jsonld
> +    "@id": "https://openminds.ebrains.eu/instances/cellType/externalTuftedCell",
https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/tufted-cell

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/middleTuftedCell.jsonld
> +    "description": "Each tufted cell is characterized by usually a single short primary dendrite that traverses the outer external plexiform layer and terminates within an olfactory glomerulus in a t
citation of source is missing

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/middleTuftedCell.jsonld
> +    "definition": "Principal neuron located in the outer third of the external plexiform layer of the olfactory bulb in the mammalian central nervous system.",
citation of source is missing

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/middleTuftedCell.jsonld
> +    "synonym": null
synoyms are missing

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/middleTuftedCell.jsonld
> +    "preferredOntologyIdentifier": null,
we should discuss if this should be interlex if interlex is the defining ontological source

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/tuftedCell.jsonld
> +    "definition": "Output cells similar to mitral cells but located more superficially in the external plexiform layer are called tufted cells (Shepherd 2004)",
please make the citation a link if possible

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/externalTuftedCell.jsonld
> +    "@id": "https://openminds.ebrains.eu/instances/cellType/externalTuftedCell",
or is external tufted cell even a fourth sub type?

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/mitralCell.jsonld
> +    "definition": "Mitral cells are a neuronal cell type in the mammalian olfactory bulb, distinguished by the position of their somata located in an orderly row in the mitral cell layer of the bulb.
citation of source is missing

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/mitralCell.jsonld
> +    "description": "Principal neuron located in the olfactory bulb in the mammalian central nervous system. The cell bodies are arranged in a thin layer between the granule cell layer and the externa
citation of source is missing

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/mitralCell.jsonld
> +    "knowledgeSpaceLink": null,
I think this is this one: https://knowledge-space.org/wiki/NIFEXT:120#olfactory-bulb-main-mitral-cell

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/mitralCell.jsonld
> +    "preferredOntologyIdentifier": null,
interlex?

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/mitralCell.jsonld
> +    "synonym": null
missing

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/periglomerularCell.jsonld
> +    "synonym": null
missing

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/periglomerularCell.jsonld
> +    "knowledgeSpaceLink": null,
missing: https://knowledge-space.org/wiki/NLXCELL:091202#olfactory-bulb-main-periglomerular-cell

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/periglomerularCell.jsonld
> +    "definition": "Small intrinsic neuron in the glomerular layer of the olfactory bulb, with cell bodies surrounding the olfactory glomerulus.",
citation of source is missing

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/periglomerularCell.jsonld
> +    "description": " The cell body is 6-8 um in diameter, from which arises a short bushy dendrite that arborizes within a glomerulus, where it receives synaptic input from olfactory receptor cell ax
citation of source is missing

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/periglomerularCell.jsonld
> +    "preferredOntologyIdentifier": null,
interlex?

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/tuftedCell.jsonld
> +    "definition": "Output cells similar to mitral cells but located more superficially in the external plexiform layer are called tufted cells (Shepherd 2004)",
this definition should be improved

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/tuftedCell.jsonld
> +    "definition": "Output cells similar to mitral cells but located more superficially in the external plexiform layer are called tufted cells (Shepherd 2004)",
e.g.:

"Tufted cells can be found in the external plexiform layer (EPL) and glomerular layer (GL) of the olfactory bulb and should be further subdivided into the superficial, middle and deep tufted cells of the EPL and the external tufted cells of the GL (Cajal, R. S. Y., 1890; Pinching, A. J. and Powell, T. P., 1971; Macrides, F. and Schneider, S. P., 1982; Orona, E. et al., 1984; Ennis, M., et al., 2007)." 

Cajal, R. S. Y., 1890: ?
Pinching, A. J. and Powell, T. P., 1971: https://doi.org/10.1242/jcs.9.2.305
Macrides, F. and Schneider, S. P., 1982: https://doi.org/10.1002/cne.902080410
Orona, E. et al., 1984: https://doi.org/10.1002/cne.902260305
Ennis, M., et al., 2007: https://doi.org/10.1007/978-0-387-30374-1_6

2023-11-27 11:23 UTC, lzehl commented on instances/cellType/externalTuftedCell.jsonld
> +    "@id": "https://openminds.ebrains.eu/instances/cellType/externalTuftedCell",
clarified this question I think in my comment for the superclass "tufted cells" (which means that I think two subtypes are missing from this PR which we should add as well)

2024-05-07 12:49 UTC, UlrikeS91 commented
replaced by https://github.com/openMetadataInitiative/openMINDS_instances/pull/87

2024-05-07 12:50 UTC, closed without merging