Adding alloy to chemical mixture type
HumanBrainProject/openMINDS_controlledTerms pull request #460
Opened 2023-11-24 14:40 UTC by Peyman-N

2023-11-25 10:05 UTC, lzehl requested changes

2023-11-25 10:05 UTC, lzehl commented on instances/chemicalMixtureType/alloy.jsonld
> +  "name": "Alloy",
please do not capitalize

2023-11-25 10:05 UTC, lzehl commented on instances/chemicalMixtureType/alloy.jsonld
> +  "definition": "A mixture consisting of a combination of metals or of a metal and another element that retains the characteristics of a metal.",
Please always add your source that you used for the definition. 

We should discuss if we either always want to start with the name of the entity we are defining or not. I would like to harmonize this a bit.

2023-11-25 10:05 UTC, lzehl commented on instances/chemicalMixtureType/alloy.jsonld
> +  "description": "",
this should be null if it is not provided

2024-05-07 11:27 UTC, UlrikeS91 commented
replaced by https://github.com/openMetadataInitiative/openMINDS_instances/pull/86

2024-05-07 11:27 UTC, closed without merging