Adding new units of measurement
HumanBrainProject/openMINDS_controlledTerms pull request #461
Opened 2023-11-24 14:42 UTC by Peyman-N

2023-11-25 10:17 UTC, lzehl requested changes
We should discuss conventions here. I'm unsure if my suggestions are the best solution for definitions.

2023-11-25 10:17 UTC, lzehl commented on instances/unitOfMeasurement/hertz.jsonld
> +  "definition": "Hertz is the unit of frequency in the International System of Units (SI), equivalent to one event (or cycle) per second.",
The hertz is ... AND please add the source of that definition (here is is Wikipedia).

2023-11-25 10:17 UTC, lzehl commented on instances/unitOfMeasurement/kilohertz.jsonld
> +  "definition": "A unit of frequency equal to one thousand cycles per second; one thousand hertz.",
please match form of definition used for hertz

2023-11-25 10:17 UTC, lzehl commented on instances/unitOfMeasurement/kilovolt.jsonld
> +  "definition": "One thousand volts.",
please match the definition form you used for hertz/kilohertz (here naturally vold / kilovolt)

2023-11-25 10:17 UTC, lzehl commented on instances/unitOfMeasurement/microvolt.jsonld
> +  "definition": "One millionth (10^-6) of a volt.",
please adapt (see previous comments)

2023-11-25 10:17 UTC, lzehl commented on instances/unitOfMeasurement/nanovolt.jsonld
> +  "definition": " one billionth (10^-9) of a volt.",
correct (unnecessary space) and see above

2023-11-27 12:03 UTC, Peyman-N commented
I completely agree we should standardize the definition all of the SI prefixes. 

I would suggest this definition :

A unit of `measurand` equivalent to `amount of` `main unit`.
Example:
A unit of **electric potential** equivalent to **_one thousand_** **volts**.

Or we can go the hard way and separate the SI prefixes from the unit, this can be beneficial in long run but would need a clean up; so I am against it.

2023-11-27 12:05 UTC, apdavison commented
> A unit of `measurand` equivalent to `amount of` `main unit`.

"equal to", not "equivalent to"

2023-12-20 13:53 UTC, apdavison requested changes
one small change: remove "KV" from synonyms

2023-12-20 13:53 UTC, apdavison commented on instances/unitOfMeasurement/kilovolt.jsonld
> +    "KV"
I don't think we should list such non-standard forms as "KV"

2023-12-20 14:03 UTC, lzehl approved these changes
under the condition to remove KV from synonyms of kilovolt as @apdavison suggests.

2023-12-21 12:17 UTC, apdavison approved these changes

2023-12-21 12:18 UTC, merged