Create molecularEntity Terminology
HumanBrainProject/openMINDS_controlledTerms pull request #85
Opened 2021-11-17 11:14 UTC by lzehl

related to #83 

Include steps:
1) create controlledTerms schema
2) add molecularEntity to terminology list
3) add first set of instances for molecularEntity

@UlrikeS91 let me know if I missed something.

2021-12-07 16:19 UTC, lzehl commented
@UlrikeS91 first set of instances (as well as the schema) for molecular entities are ready for review :)

2021-12-08 08:03 UTC, UlrikeS91 requested changes

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/GABA-A_BZ.jsonld
> +    "definition": "The GABA-A/BZ is a distinct binding site for benzodiazepines that is situated at the interface between the \u03b1- and \u03b3-subunits of \u03b1- and \u03b3-subunit containing GABA
" [...] \u03b1- and \u03b3-subunits of \u03b1- and \u03b3-subunit containing [...]" 

Is this on purpose? It sounds a bit odd and the subunits generally are pretty cryptic. Any way to revise this?

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/alpha-1Receptor.jsonld
> +    "definition": "The alpha-1 receptor is a subclass of the  adrenoceptor group that bind epinephrine or norepinephrine as endogenous ligands.",
there is an extra space between "the" and "adrenoceptor"

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/alpha-1Receptor.jsonld
> +        "\u03b11 adrenergic receptor"
same comment as above. rather cryptic, but I guess it is correct?

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/alpha-2Receptor.jsonld
> +        "\u03b12 adrenergic receptor"
same comment as above. rather cryptic, but I guess it is correct?

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/alpha-2Receptor.jsonld
> +    "definition": "The alpha-2 receptor is a subclass of the  adrenoceptor group that bind epinephrine or norepinephrine as endogenous ligands.",
also has the extra space

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/alpha-4Beta-2Receptor.jsonld
> +        "\u03b14\u03b22 receptor"
same comment as above. rather cryptic, but I guess it is correct?

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/anterogradeTracer.jsonld
> +    "synonym": []
needs to be "null" if no synonyms are listed

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/anterogradeTracer.jsonld
> +    "definition": "Molecule that is taken up by the cell bodies of neurons and transported towards the axon terminals, used for anterograde tract tracing studies in the nervous system.",
I would not say "cell bodies". This is typically the main place, but not exclusively. Maybe:

"Molecule that is taken up by neurons (e.g., by viral transfection mechanisms, by other cell internalization mechanisms or passive diffusion) and transported towards the axon terminals, used for anterograde tract tracing studies in the nervous system."

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/biomarker.jsonld
> +    "synonym": []
needs to be "null" if no synonyms are listed

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/biotinylatedDextranAmine.jsonld
> +    "definition": "A 'biotinylated dextran amine' is an organic compound which is used as an anterograde and retrograde neuroanatomical tracers.",
"[...] as an [...] tracer." or "[...] as [...] tracers." (I would prefer singular "tracer")

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/calciumCalmodulinProteinKinaseIi.jsonld
> +    "@id": "https://openminds.ebrains.eu/instances/molecularEntity/calciumCalmodulinProteinKinaseIi",
calciumCalmodulinProteinKinaseIi --> calciumCalmodulinProteinKinaseI**I** (Kinase II, the lower case second i is wrong)

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/calciumCalmodulinProteinKinaseIi.jsonld
> +    "definition": "The 'calcium calmodulin protein kinase II' is a protein with a core domain architecture consisting of a Protein kinase domain and a C-terminal Calcium/calmodulin dependent protein
"[...] of a Protein kinase domain a [...]" -- protein lowercase?

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/calciumCalmodulinProteinKinaseIiAlphaChain.jsonld
> +    "@id": "https://openminds.ebrains.eu/instances/molecularEntity/calciumCalmodulinProteinKinaseIiAlphaChain",
the Kinase II i again

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/fluorescentMicrospheres.jsonld
> +    "synonym": []
needs to be "null" if no synonyms are listed

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/growthFactor.jsonld
> +    "definition": "The \"growth factor\" comprises signal molecules that are involved in the control of cell growth and differentiation.",
maybe just make the " into ' around 'growth factor'?

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/intrabody.jsonld
> +    "synonym": []
needs to be "null" if no synonyms are listed

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/intrabody.jsonld
> +    "definition": "An \"intrabody\" is an antibody that works within the cell to bind an intracellular protein.",
maybe just make the " into ' around 'intrabody'?

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/medetomidine.jsonld
> +    "synonym": []
needs to be "null" if no synonyms are listed

2021-12-08 08:03 UTC, UlrikeS91 commented on instances/molecularEntity/neurobiotin.jsonld
> +    "synonym": []
needs to be "null" if no synonyms are listed

2021-12-08 08:18 UTC, lzehl commented on instances/molecularEntity/GABA-A_BZ.jsonld
> +    "definition": "The GABA-A/BZ is a distinct binding site for benzodiazepines that is situated at the interface between the \u03b1- and \u03b3-subunits of \u03b1- and \u03b3-subunit containing GABA
@olinux how should we deal with special characters ? (especially in molecular entities we will have a need for them for correct names)

2021-12-08 08:21 UTC, lzehl commented on instances/molecularEntity/anterogradeTracer.jsonld
> +    "definition": "Molecule that is taken up by the cell bodies of neurons and transported towards the axon terminals, used for anterograde tract tracing studies in the nervous system.",
see revised definition

2021-12-08 08:34 UTC, lzehl commented on instances/molecularEntity/GABA-A_BZ.jsonld
> +    "definition": "The GABA-A/BZ is a distinct binding site for benzodiazepines that is situated at the interface between the \u03b1- and \u03b3-subunits of \u03b1- and \u03b3-subunit containing GABA
@olinux confirmed it should be interpreted correctly

2021-12-08 08:48 UTC, lzehl commented on instances/molecularEntity/intrabody.jsonld
> +    "synonym": []
should be null now

2021-12-08 08:48 UTC, lzehl commented on instances/molecularEntity/intrabody.jsonld
> +    "definition": "An \"intrabody\" is an antibody that works within the cell to bind an intracellular protein.",
done

2021-12-08 08:48 UTC, lzehl commented on instances/molecularEntity/medetomidine.jsonld
> +    "synonym": []
done

2021-12-08 09:19 UTC, UlrikeS91 approved these changes

2021-12-08 09:19 UTC, merged